ALTER TABLE IF EXISTS reservations
ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS success_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS fail_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS terminated_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS canceled_at TIMESTAMPTZ;
